#!/usr/bin/env python3
"""
AI Firewall Policy Optimizer - CLI

Usage examples:
  python main.py --rules sample_rules.csv --output report.md
  python main.py --rules rules.csv --hits hits.csv --format json
"""

import click
import pandas as pd
from pathlib import Path
from rich.console import Console
from firewall_analyzer import FirewallAnalyzer, load_rules_from_csv, Rule

console = Console()

@click.command()
@click.option("--rules", required=True, type=click.Path(exists=True), help="CSV file with firewall rules")
@click.option("--hits", default=None, type=click.Path(exists=True), help="Optional CSV with hit counts")
@click.option("--output", default="policy_report.md", help="Output file (md or json)")
@click.option("--format", "fmt", default="md", type=click.Choice(["md", "json"]), help="Output format")
def analyze(rules, hits, output, fmt):
    console.print("[bold blue]Loading rules...[/bold blue]")
    rule_list = load_rules_from_csv(rules)

    # Merge hit counts if provided
    if hits:
        hits_df = pd.read_csv(hits)
        hit_map = dict(zip(hits_df.iloc[:,0].astype(str), hits_df.iloc[:,1].astype(int)))
        for r in rule_list:
            if r.name in hit_map:
                r.hit_count = hit_map[r.name]

    analyzer = FirewallAnalyzer(rule_list)
    result = analyzer.analyze()

    if fmt == "json":
        import json
        data = {
            "summary": {
                "total": result["total_rules"],
                "high_risk_count": len(result["high_risk"]),
                "shadowed_count": len(result["shadowed"]),
            },
            "high_risk": [r.name for r in result["high_risk"]],
            "shadowed": result["shadowed"],
        }
        Path(output).write_text(json.dumps(data, indent=2))
        console.print(f"[green]JSON report written to {output}[/green]")
    else:
        analyzer.print_summary(result)
        # Write a simple markdown report
        md = generate_markdown_report(result)
        Path(output).write_text(md)
        console.print(f"\n[green]Markdown report written to {output}[/green]")

def generate_markdown_report(result: dict) -> str:
    lines = ["# Firewall Policy Optimization Report\n"]
    lines.append(f"**Total rules analyzed:** {result['total_rules']}\n")

    if result["high_risk"]:
        lines.append("## High Risk Rules\n")
        lines.append("| Rule | Risk Score | Notes |")
        lines.append("|------|------------|-------|")
        for r in result["high_risk"]:
            notes = []
            if r.is_any_any(): notes.append("any/any")
            if r.hit_count == 0: notes.append("0 hits")
            lines.append(f"| {r.name} | {r.risk_score()} | {', '.join(notes)} |")

    if result["shadowed"]:
        lines.append("\n## Shadowed Rules\n")
        for s in result["shadowed"]:
            lines.append(f"- `{s['shadowed_rule']}` is shadowed by `{s['by_rule']}`")

    lines.append("\n> Generated by AI Firewall Policy Optimizer\n")
    return "\n".join(lines)

if __name__ == "__main__":
    analyze()
